version: "3.8"

services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env.production
    ports:
      - "4001:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://192.168.1.42:4001   # 👈 ton IP locale ici
    env_file:
      - ./frontend/.env.production
    ports:
      - "3001:80"
    restart: unless-stopped
